import sys
import traceback
import os
import json
from datetime import datetime

class AutoLogger:
    """
    The Pythonic+ Forensic Integrity Guard.
    
    This class overrides the default Python exception handling mechanism. 
    Instead of allowing the interpreter to crash and close the terminal 
    immediately, it captures a 'Black Box' state of the application, 
    hardware signature, and any active loop progress.

    Usage:
        >>> from pplus.system.logger import AutoLogger
        >>> logger = AutoLogger("MyProject", "AMD64-8Cores")
        >>> # Any unhandled exception from here on is caught.
    """

    def __init__(self, name: str, hardware_info: str):
        """
        Initialize the logger and hijack the system exception hook.

        Args:
            name (str): The name of the project as defined in .pyproj.
            hardware_info (str): Hardware string generated by HardwareRecon.
        """
        self.name = name
        self.hw = hardware_info
        
        # Globally intercept unhandled exceptions
        sys.excepthook = self.handle_crash

    def _get_last_checkpoint(self) -> str:
        """
        Internal helper to locate HyperLoop checkpoint files.
        
        Scans the current working directory for temporary state files 
        to help developers identify exactly where a long-running 
        process failed.

        Returns:
            str: A descriptive string of the last known execution index.
        """
        # Look for the hidden checkpoint file pattern
        checkpoints = [f for f in os.listdir('.') if f.startswith(".pplus_checkpoint_")]
        if not checkpoints:
            return "Execution State: Idle / No Active Loops"
        
        try:
            with open(checkpoints[0], 'r', encoding='utf-8') as f:
                data = json.load(f)
                idx = data.get('last_index', 'Unknown')
                return f"Execution State: Interrupted at Index {idx}"
        except (IOError, json.JSONDecodeError):
            return "Execution State: Checkpoint data corrupted"

    def handle_crash(self, etype, value, tb):
        """
        The Forensic Handler for system-wide exceptions.
        
        Writes a detailed crash report to 'crash_report.log' including 
        timestamp, hardware specs, and a full stack trace. Prevents 
        the terminal window from closing until user acknowledgement.

        Args:
            etype: The type of the exception.
            value: The exception instance/message.
            tb: The traceback object.
        """
        log_file = "crash_report.log"
        checkpoint_context = self._get_last_checkpoint()
        
        try:
            # We use 'a' (append) to preserve history of previous crashes
            with open(log_file, "a", encoding="utf-8") as f:
                f.write(f"\n{'='*60}\n")
                f.write(f"CRASH REPORT GENERATED: {datetime.now()}\n")
                f.write(f"Project Name: {self.name}\n")
                f.write(f"Hardware Spec: {self.hw}\n")
                f.write(f"Context: {checkpoint_context}\n")
                f.write(f"{'-'*60}\n")
                
                # Format and write the Python traceback
                traceback.print_exception(etype, value, tb, file=f)
                f.write(f"{'='*60}\n")
        except Exception as logger_internal_error:
            # If the logger fails (e.g., Disk Full), we fall back to stderr
            sys.stderr.write(f"Logger Error: {logger_internal_error}\n")

        # Visual feedback for the developer in the terminal
        print(f"\n[!] PYTHONIC+ ARCHITECTURE GUARD: FATAL ERROR")
        print(f"[*] Forensic log saved: {log_file}")
        print(f"[*] {checkpoint_context}")
        
        # Prevents window closure in standalone execution environments
        input("\n[TERMINATED] Press Enter to acknowledge and exit...")